public class GeometryLabTest {
    
    public static void main(String[] args) {
        GeometryLab Geo = new GeometryLab();
        System.out.println(Geo.f(2,3));
        System.out.println(Geo.f(4,8));
        System.out.println(Geo.g(3,5));
        System.out.println(Geo.g(5,3));
        System.out.println(Geo.h(2,9));
        System.out.println(Geo.h(4,10));
        System.out.println(Geo.j(5,10));
        System.out.println(Geo.j(10,5));
        System.out.println(Geo.k(9,7));
        System.out.println(Geo.k(7,9));
        System.out.println(Geo.m(3,4,5));
        System.out.println(Geo.m(4,6,3));
        System.out.println(Geo.f(Geo.g(3,5), Geo.k(7,9)));
        System.out.println(Geo.f(Geo.j(10,5), Geo.h(2,9)));
        System.out.println(Geo.g(Geo.m(3,4,5), Geo.h(4,10)));
        System.out.println(Geo.g(Geo.j(5,10), Geo.f(2,3)));
        System.out.println(Geo.j(Geo.k(7,9), Geo.g(3,5)));
        System.out.println(Geo.j(Geo.h(2,9), Geo.m(4,6,3)));
        System.out.println(Geo.k(Geo.m(3,4,5), Geo.j(10,5)));
        System.out.println(Geo.k(Geo.k(9,7), Geo.f(4,8)));
        System.out.println(Geo.m(Geo.h(4,10), Geo.f(2,3), Geo.g(5,3)));
        System.out.println(Geo.m(Geo.k(7,9), Geo.j(5,10), Geo.h(4,10)));
        System.out.println(Geo.triArea(2,3));
        System.out.println(Geo.triArea(4,8));
        System.out.println(Geo.trapArea(3,4,5));
        System.out.println(Geo.trapArea(4,6,3));
        System.out.println(Geo.rectArea(3,5));
        System.out.println(Geo.rectArea(5,3));
        System.out.println(Geo.circArea(7));
        System.out.println(Geo.circArea(9));
        System.out.println(Geo.paralArea(2,9));
        System.out.println(Geo.paralArea(4,19));
        System.out.println(Geo.pythHypothenuse(5,10));
        System.out.println(Geo.pythHypothenuse(9,7));
        System.out.println(Geo.triPrismVol(10,5,4));
        System.out.println(Geo.triPrismVol(7,9,3));
        System.out.println(Geo.rectPrismVol(2,3,4));
        System.out.println(Geo.rectPrismVol(8,3,6));
        System.out.println(Geo.rectPyramidVol(5,7,9));
        System.out.println(Geo.rectPyramidVol(4,6,8));
        System.out.println(Geo.cylVol(9,2));
        System.out.println(Geo.cylVol(10,3));
        System.out.println(Geo.spherevol(6));
        System.out.println(Geo.spherevol(8));
        System.out.println(Geo.coneVol(6,5));
        System.out.println(Geo.coneVol(8,7));
        System.out.println(Geo.sphereSurfArea(4));
        System.out.println(Geo.sphereSurfArea(7));
        System.out.println(Geo.cylSurfArea(4, 7));
        System.out.println(Geo.cylSurfArea(5, 3));
        System.out.println(Geo.rectPrismSurfArea(2,3,4));
        System.out.println(Geo.rectPrismSurfArea(8,3,6));
        System.out.println(Geo.triArea(Geo.f(2,3), Geo.h(4,8)));
        System.out.println(Geo.rectArea(Geo.g(7,5), Geo.j(5,3)));
        System.out.println(Geo.trapArea(Geo.m(3,4,5),Geo.m(4,6,3),Geo.m(8,3,6)));
        System.out.println(Geo.circArea(Geo.k(8,5)));
        System.out.println(Geo.paralArea(Geo.j(9,2), Geo.f(4,10)));
        System.out.println(Geo.pythHypothenuse(Geo.f(5,10),Geo.g(9,7)));
        System.out.println(Geo.triPrismVol(Geo.m(10,5,4),Geo.m(7,9,3),Geo.m(5,7,3)));
        System.out.println(Geo.rectPrismVol(Geo.h(2,4), Geo.m(8,6,3), Geo.k(20,7)));
        System.out.println(Geo.rectPyramidVol(Geo.m(5,7,9), Geo.m(4, 6, 8), Geo.k(20,7)));
        System.out.println(Geo.cylVol(Geo.h(9,2), Geo.k(10, 3)));
        System.out.println(Geo.spherevol(Geo.g(9,6)));
        System.out.println(Geo.coneVol(Geo.j(6,5), Geo.j(8,7)));
        System.out.println(Geo.sphereSurfArea(Geo.m(4,3,1)));
        System.out.println(Geo.cylSurfArea(4,Geo.f(5,3)));
        System.out.println(Geo.rectPrismSurfArea(Geo.pythHypothenuse(3,4),3, Geo.k(13, 5)));
    }
}